### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 28: invalid start byte

### ISSUE THREAD

**Issue by jaydensmith** [JazzCore/python-pdfkit#70]
Latest release has introduced a new bug (this same code worked on 0.5.0)

```
File "/usr/local/lib/python3.5/dist-packages/pdfkit/api.py", line 72, in from_string
   return r.to_pdf(output_path)

 File "/usr/local/lib/python3.5/dist-packages/pdfkit/pdfkit.py", line 146, in to_pdf
   if 'cannot connect to X server' in stderr.decode('utf-8'):

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 28: invalid start byte
```

**Comment by orporat** [comment]
I can confirm I've also encountered this bug with 0.6.0

**Comment by anderspetersson** [comment]
I'm getting this if I pass {'quiet': ''} to options in from_string

**Comment by JazzCore** [comment]
Should be fixed in #72

**Comment by vbukhonov** [comment]
Getting the same error.

**Comment by morganzysman** [comment]
Any update on this ?

**Comment by Schnodderbalken** [comment]
I can definitely confirm that this issue still persists von version 0.6.1.
I tried it in a clean docker environment. In order to reproduce this error, the following command is enough:
`pdfkit.from_string(html_result, 'string').to_pdf(False).decode()`.
This leads to:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 785: invalid start byte`

@JazzCore do you have any idea why this is?
